

import type { Metadata } from "next";
import localFont from "next/font/local";
// Importa Bootstrap + Popper.js
import "./globals.css";
import InstallBootstrap from "@/components/InstallBootstrap";
import BotaoVoltar from "@/components/BotaoVoltar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sorveteria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         {/* Botão Voltar */}
         <BotaoVoltar />
        <InstallBootstrap/>
        {children}
      </body>
    
    </html>
  );
}
